### ISSUE TITLE
Проблема с тестами сервера для спринта 3

### ISSUE THREAD

**Issue by lleri** [cpppracticum/cpp-backend-template-practicum#10]
В тестах test_s03_gen_objects.py, test_s03_find_return.py и test_s03_scores.py выдается одна и та же ошибка: https://pastebin.com/maf90WyR и локально и в github actions.
Проблема, похоже, заключается в объявлении тестовой функции test_map_not_found в параметре map_id:
@pytest.mark.parametrize('method', ['GET', 'HEAD'])
@pytest.mark.randomize(min_length=1, max_length=15, str_attrs=('digits', 'ascii_letters'), ncalls=3)
def test_map_not_found(server, method, **map_id: str**):
    header = {}
    request = f'api/v1/maps/__{map_id}'
...

При этом, если удалить **:str** :
@pytest.mark.parametrize('method', ['GET', 'HEAD'])
@pytest.mark.randomize(min_length=1, max_length=15, str_attrs=('digits', 'ascii_letters'), ncalls=3)
def test_map_not_found(server, method, **map_id**):
    header = {}
    request = f'api/v1/maps/__{map_id}'
...

То всё работает прекрасно.

**Comment by wo1f** [comment]
Не в ту репу issue, но я поправил)
